import { z } from "zod";

export const ProvisionUpdateSchema = z.object({
  code: z.string(),
  ch: z.string(),
  chName: z.string(),
  sec: z.string(),
  sub: z.string(),
  title: z.string(),
  summary: z.string(),
  fullText: z.string(),
  impact: z.enum(["Critical", "High", "Medium", "Low"]),
  ruleAuth: z.enum([
    "Central Government",
    "State Government",
    "Appropriate Government",
    "Central & State Government",
    "Not Applicable",
  ]),
  changeTags: z.array(z.string()).optional(),
  workflowTags: z.array(z.string()).optional(),
  penaltyOld: z.string().optional(),
  penaltyNew: z.string().optional(),
  notes: z.string().optional(),
  assignee: z.string().optional(),
  dueDate: z.string().optional().nullable(),
  verified: z.boolean().optional(),
  pinned: z.boolean().optional(),
  oldMappings: z.array(z.object({
    act: z.string(),
    sec: z.string(),
    summary: z.string(),
    fullText: z.string(),
    change: z.string(),
    changeTags: z.array(z.string()).optional(),
  })).optional(),
  compItems: z.array(z.object({
    task: z.string(),
    assignee: z.string(),
    due: z.string().optional().nullable(),
    status: z.string().optional(),
  })).optional(),
  stateNotes: z.record(z.string(), z.string()).optional(),
  stateRuleText: z.record(z.string(), z.string()).optional(),
  stateCompStatus: z.record(z.string(), z.string()).optional(),
});
