"use client";

import { useUI } from "@/context/UIContext";
import { X, Download, Printer, FileText } from "lucide-react";
import { useEffect, useState } from "react";

export function PDFPreviewModal() {
  const { pdfBlobUrl, setPdfBlobUrl } = useUI();
  const [isClosing, setIsClosing] = useState(false);

  useEffect(() => {
    if (pdfBlobUrl) {
      setIsClosing(false);
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => { document.body.style.overflow = ''; };
  }, [pdfBlobUrl]);

  if (!pdfBlobUrl) return null;

  const handleClose = () => {
    setIsClosing(true);
    setTimeout(() => {
      setPdfBlobUrl(null);
    }, 200);
  };

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = pdfBlobUrl;
    link.download = `Labour_Code_Review_${new Date().toISOString().split('T')[0]}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrint = () => {
    const iframe = document.getElementById('pdf-iframe') as HTMLIFrameElement;
    if (iframe && iframe.contentWindow) {
      iframe.contentWindow.print();
    }
  };

  return (
    <div 
      className={`fixed inset-0 z-[1100] flex items-center justify-center p-4 transition-all duration-300 ${
        isClosing ? 'opacity-0 scale-95' : 'opacity-100 scale-100'
      }`}
    >
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-900/40 dark:bg-zinc-950/60 backdrop-blur-xl"
        onClick={handleClose}
      />

      {/* Modal */}
      <div className="relative bg-white dark:bg-zinc-900 w-full max-w-5xl h-[90vh] rounded-3xl shadow-2xl border border-white/20 dark:border-zinc-800 overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-zinc-800 bg-slate-50/50 dark:bg-zinc-900/50 backdrop-blur-md">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-500/10 rounded-xl">
              <FileText className="w-5 h-5 text-blue-500" />
            </div>
            <div>
              <h3 className="text-sm font-black uppercase tracking-widest text-slate-900 dark:text-zinc-100">
                PDF Preview
              </h3>
              <p className="text-[10px] text-slate-500 dark:text-zinc-400 font-bold uppercase tracking-wider">
                High-Fidelity Document Generation
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-[11px] font-black uppercase tracking-widest transition-all shadow-lg shadow-blue-500/20 active:scale-95 cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              Download
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-4 py-2 bg-slate-900 dark:bg-zinc-100 text-white dark:text-zinc-900 rounded-xl text-[11px] font-black uppercase tracking-widest hover:bg-slate-800 dark:hover:bg-white transition-all shadow-lg shadow-slate-900/10 active:scale-95 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              Print
            </button>
            <div className="w-px h-6 bg-slate-200 dark:bg-zinc-800 mx-1" />
            <button
              onClick={handleClose}
              className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-zinc-200 hover:bg-slate-100 dark:hover:bg-zinc-800 rounded-xl transition-all cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 bg-slate-100 dark:bg-zinc-950 p-4 overflow-hidden">
          <iframe 
            id="pdf-iframe"
            src={pdfBlobUrl} 
            className="w-full h-full rounded-2xl shadow-inner border border-slate-200 dark:border-zinc-800 bg-white"
          />
        </div>

        {/* Footer info */}
        <div className="px-6 py-3 bg-white dark:bg-zinc-900 text-center border-t border-slate-100 dark:border-zinc-800">
          <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">
            Generated by Labour Code intelligence platform · March 2026
          </p>
        </div>
      </div>
    </div>
  );
}
