import { CodeKey } from "@/types/code";

// Tracked states/jurisdictions
export const STATES = [
  "Centre",
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

export type TrackedState = (typeof STATES)[number];

const defaultStatus = { CoW: "Not Published", IRC: "Not Published", CoSS: "Not Published", OSHW: "Not Published" };

// State-wise rule status
export const STATE_RULE_STATUS: Record<
  TrackedState,
  Record<CodeKey, string>
> = {
  Centre: { CoW: "Draft", IRC: "Draft", CoSS: "Draft", OSHW: "Draft" },
  Delhi: { CoW: "Final", IRC: "Draft", CoSS: "Final", OSHW: "Draft" },
  Karnataka: { CoW: "Final", IRC: "Final", CoSS: "Draft", OSHW: "Draft" },
  Maharashtra: { CoW: "Final", IRC: "Final", CoSS: "Final", OSHW: "Final" },
  "Tamil Nadu": { CoW: "Draft", IRC: "Draft", CoSS: "Not Published", OSHW: "Draft" },
  Telangana: { CoW: "Draft", IRC: "Draft", CoSS: "Draft", OSHW: "Draft" },
  "Andaman and Nicobar Islands": defaultStatus,
  "Andhra Pradesh": defaultStatus,
  "Arunachal Pradesh": defaultStatus,
  "Assam": defaultStatus,
  "Bihar": defaultStatus,
  "Chandigarh": defaultStatus,
  "Chhattisgarh": defaultStatus,
  "Dadra and Nagar Haveli and Daman and Diu": defaultStatus,
  "Goa": defaultStatus,
  "Gujarat": defaultStatus,
  "Haryana": defaultStatus,
  "Himachal Pradesh": defaultStatus,
  "Jammu and Kashmir": defaultStatus,
  "Jharkhand": defaultStatus,
  "Kerala": defaultStatus,
  "Ladakh": defaultStatus,
  "Lakshadweep": defaultStatus,
  "Madhya Pradesh": defaultStatus,
  "Manipur": defaultStatus,
  "Meghalaya": defaultStatus,
  "Mizoram": defaultStatus,
  "Nagaland": defaultStatus,
  "Odisha": defaultStatus,
  "Puducherry": defaultStatus,
  "Punjab": defaultStatus,
  "Rajasthan": defaultStatus,
  "Sikkim": defaultStatus,
  "Tripura": defaultStatus,
  "Uttar Pradesh": defaultStatus,
  "Uttarakhand": defaultStatus,
  "West Bengal": defaultStatus,
};
