"""Initial 22-table schema

Revision ID: 0694a967ee8b
Revises: 
Create Date: 2026-03-19 03:37:45.203661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0694a967ee8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short_title', sa.Text(), nullable=True),
    sa.Column('popular_name', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('ACT', 'RULE', 'REGULATION', 'ORDINANCE', 'NOTIFICATION', 'CIRCULAR', 'ORDER', 'GUIDELINES', 'DIRECTIVE', 'TREATY', 'CONVENTION', 'SCHEME', 'POLICY', 'CODE', 'MANUAL', 'STANDARD', name='documenttype'), nullable=True),
    sa.Column('document_number', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('jurisdiction_country', sa.Text(), nullable=True),
    sa.Column('jurisdiction_state', sa.Text(), nullable=True),
    sa.Column('jurisdiction_local', sa.Text(), nullable=True),
    sa.Column('issuing_authority', sa.Text(), nullable=True),
    sa.Column('gazette_reference', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('date_of_assent', sa.Date(), nullable=True),
    sa.Column('date_of_publication', sa.Date(), nullable=True),
    sa.Column('default_commencement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REPEALED', 'EXPIRED', 'SUSPENDED', 'NOT_YET_COMMENCED', 'PARTIALLY_COMMENCED', 'SUPERSEDED', name='documentstatus'), nullable=True),
    sa.Column('sunset_date', sa.Date(), nullable=True),
    sa.Column('subject_categories', sa.JSON(), nullable=True),
    sa.Column('is_connector_act', sa.Boolean(), nullable=True),
    sa.Column('connector_act_type', sa.String(), nullable=True),
    sa.Column('plain_language_summary', sa.Text(), nullable=True),
    sa.Column('preamble_text', sa.Text(), nullable=True),
    sa.Column('enacting_formula', sa.Text(), nullable=True),
    sa.Column('long_title', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('editor_notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_transaction_id', sa.UUID(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transaction_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('authority_type', sa.Text(), nullable=True),
    sa.Column('parent_authority_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction', sa.Text(), nullable=True),
    sa.Column('governing_act_id', sa.UUID(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['governing_act_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_authority_id'], ['authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_circulars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('notification_number', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.Text(), nullable=True),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('provisions_affected', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('supersedes_notification_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['supersedes_notification_id'], ['notifications_circulars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structural_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('unit_type', sa.Enum('PREAMBLE', 'PART', 'CHAPTER', 'SECTION', 'SUBSECTION', 'CLAUSE', 'SUBCLAUSE', 'PARAGRAPH', 'SUBPARAGRAPH', 'ITEM', 'POINT', 'RULE', 'SUBRULE', 'ARTICLE', 'SCHEDULE', 'APPENDIX', 'ANNEXURE', 'TABLE', 'PROVISO', 'EXPLANATION', 'ILLUSTRATION', 'EXCEPTION', 'NOTE', 'FORM', 'ENTRY', name='unittype'), nullable=True),
    sa.Column('number', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('heading_note', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('plain_language_summary', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('depth_level', sa.Integer(), nullable=True),
    sa.Column('commencement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('provision_nature', sa.JSON(), nullable=True),
    sa.Column('compliance_type', sa.Text(), nullable=True),
    sa.Column('compliance_trigger_event', sa.Text(), nullable=True),
    sa.Column('compliance_due_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('amending_document_id', sa.UUID(), nullable=True),
    sa.Column('amending_reference', sa.Text(), nullable=True),
    sa.Column('amendment_date', sa.Date(), nullable=True),
    sa.Column('nature_of_change', sa.Text(), nullable=True),
    sa.Column('previous_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('notification_reference', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amending_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicability_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('geographic_scope', sa.Text(), nullable=True),
    sa.Column('geographic_scope_tags', sa.JSON(), nullable=True),
    sa.Column('applicability_start_date', sa.Date(), nullable=True),
    sa.Column('applicability_end_date', sa.Date(), nullable=True),
    sa.Column('entity_types', sa.JSON(), nullable=True),
    sa.Column('applicable_industries', sa.JSON(), nullable=True),
    sa.Column('threshold_conditions', sa.JSON(), nullable=True),
    sa.Column('exempt_categories', sa.JSON(), nullable=True),
    sa.Column('exemption_notification_refs', sa.JSON(), nullable=True),
    sa.Column('conditional_logic', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authority_provision_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=True),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('obligation_type', sa.Text(), nullable=True),
    sa.Column('compliance_category', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('due_date_rule', sa.Text(), nullable=True),
    sa.Column('frequency_detail', sa.Text(), nullable=True),
    sa.Column('penalty_section_ref', sa.Text(), nullable=True),
    sa.Column('penalty_description', sa.Text(), nullable=True),
    sa.Column('penalty_type', sa.Text(), nullable=True),
    sa.Column('penalty_amount_or_formula', sa.Text(), nullable=True),
    sa.Column('compounding_allowed', sa.Boolean(), nullable=True),
    sa.Column('compounding_authority', sa.Text(), nullable=True),
    sa.Column('limitation_period', sa.Text(), nullable=True),
    sa.Column('responsible_role', sa.Text(), nullable=True),
    sa.Column('prescribed_form_id', sa.UUID(), nullable=True),
    sa.Column('prescribed_form_name', sa.Text(), nullable=True),
    sa.Column('prescribed_fee', sa.Text(), nullable=True),
    sa.Column('prescribed_fee_formula', sa.Text(), nullable=True),
    sa.Column('prescribed_authority', sa.Text(), nullable=True),
    sa.Column('appellate_authority', sa.Text(), nullable=True),
    sa.Column('appeal_limitation', sa.Text(), nullable=True),
    sa.Column('procedural_steps', sa.JSON(), nullable=True),
    sa.Column('second_appeal_authority', sa.Text(), nullable=True),
    sa.Column('second_appeal_limitation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prescribed_form_id'], ['structural_units.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conditions_precedent_consequent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('condition_type', sa.Text(), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('consequence_text', sa.Text(), nullable=True),
    sa.Column('consequence_unit_id', sa.UUID(), nullable=True),
    sa.Column('time_window', sa.Text(), nullable=True),
    sa.Column('applicable_entities', sa.JSON(), nullable=True),
    sa.Column('parseable_condition', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_unit_id'], ['structural_units.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cross_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_unit_id', sa.UUID(), nullable=False),
    sa.Column('target_unit_id', sa.UUID(), nullable=True),
    sa.Column('target_document_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.Enum('PARENT_ACT', 'ENABLING_SECTION', 'AMENDED_BY', 'AMENDS', 'REPEALED_BY', 'REPEALS', 'OVERRIDES', 'SUBJECT_TO', 'READ_WITH', 'PARI_MATERIA', 'INTRA_DOCUMENT', 'INTER_DOCUMENT', 'RELATED_SUBORDINATE', 'RELATED_FORM', 'RELATED_CASE_LAW', 'DELEGATED_LEGISLATION', 'CONFLICT', 'SAVINGS_CLAUSE', 'CONNECTOR_ACT', 'TRANSACTION_WORKFLOW', name='referencetype'), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_unit_id'], ['structural_units.id'], ),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['target_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('scope_note', sa.Text(), nullable=True),
    sa.Column('is_inclusive', sa.Boolean(), nullable=True),
    sa.Column('is_exhaustive', sa.Boolean(), nullable=True),
    sa.Column('related_terms', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegation_of_powers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delegating_unit_id', sa.UUID(), nullable=True),
    sa.Column('delegated_power', sa.Text(), nullable=True),
    sa.Column('delegate_authority_id', sa.UUID(), nullable=True),
    sa.Column('conditions_on_exercise', sa.Text(), nullable=True),
    sa.Column('has_been_exercised', sa.Boolean(), nullable=True),
    sa.Column('exercised_via_notification', sa.UUID(), nullable=True),
    sa.Column('exercised_via_document_id', sa.UUID(), nullable=True),
    sa.Column('sub_delegation_allowed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delegate_authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['delegating_unit_id'], ['structural_units.id'], ),
    sa.ForeignKeyConstraint(['exercised_via_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['exercised_via_notification'], ['notifications_circulars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('fee_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('slab_from', sa.Numeric(), nullable=True),
    sa.Column('slab_to', sa.Numeric(), nullable=True),
    sa.Column('fee_amount_fixed', sa.Numeric(), nullable=True),
    sa.Column('fee_percentage', sa.Numeric(), nullable=True),
    sa.Column('fee_formula', sa.Text(), nullable=True),
    sa.Column('payable_to', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('notification_reference', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('form_number', sa.Text(), nullable=True),
    sa.Column('form_name', sa.Text(), nullable=True),
    sa.Column('prescribed_under_section', sa.Text(), nullable=True),
    sa.Column('filing_authority_id', sa.UUID(), nullable=True),
    sa.Column('filing_frequency', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('fields_required', sa.JSON(), nullable=True),
    sa.Column('template_file_path', sa.Text(), nullable=True),
    sa.Column('e_filing_url', sa.Text(), nullable=True),
    sa.Column('fee', sa.Text(), nullable=True),
    sa.Column('late_fee_formula', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['filing_authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judicial_interpretations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('case_name', sa.Text(), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('court', sa.Text(), nullable=True),
    sa.Column('court_authority_id', sa.UUID(), nullable=True),
    sa.Column('date_of_judgment', sa.Date(), nullable=True),
    sa.Column('bench_strength', sa.Text(), nullable=True),
    sa.Column('ratio_decidendi', sa.Text(), nullable=True),
    sa.Column('obiter_dicta', sa.Text(), nullable=True),
    sa.Column('interpretation_type', sa.Text(), nullable=True),
    sa.Column('is_good_law', sa.Boolean(), nullable=True),
    sa.Column('overruled_by_case_id', sa.UUID(), nullable=True),
    sa.Column('distinguished_in', sa.JSON(), nullable=True),
    sa.Column('followed_in', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['court_authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['overruled_by_case_id'], ['judicial_interpretations.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_in_time_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('full_text_as_on_date', sa.Text(), nullable=True),
    sa.Column('status_as_on_date', sa.Text(), nullable=True),
    sa.Column('applicable_amendments', sa.JSON(), nullable=True),
    sa.Column('generated_from_amendments', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_slab_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('schedule_name', sa.Text(), nullable=True),
    sa.Column('slab_from', sa.Numeric(), nullable=True),
    sa.Column('slab_to', sa.Numeric(), nullable=True),
    sa.Column('rate_percentage', sa.Numeric(), nullable=True),
    sa.Column('rate_fixed_amount', sa.Numeric(), nullable=True),
    sa.Column('rate_formula', sa.Text(), nullable=True),
    sa.Column('applicable_category', sa.Text(), nullable=True),
    sa.Column('surcharge', sa.Text(), nullable=True),
    sa.Column('cess', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('amending_notification', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repeal_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repealed_unit_id', sa.UUID(), nullable=True),
    sa.Column('replacing_unit_id', sa.UUID(), nullable=True),
    sa.Column('repealing_document_id', sa.UUID(), nullable=True),
    sa.Column('mapping_type', sa.Text(), nullable=True),
    sa.Column('mapping_notes', sa.Text(), nullable=True),
    sa.Column('savings_clause_ref', sa.Text(), nullable=True),
    sa.Column('transitional_provision_ref', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['repealed_unit_id'], ['structural_units.id'], ),
    sa.ForeignKeyConstraint(['repealing_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['replacing_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rights_and_remedies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('right_or_remedy_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('who_can_invoke', sa.Text(), nullable=True),
    sa.Column('first_forum', sa.Text(), nullable=True),
    sa.Column('first_forum_authority_id', sa.UUID(), nullable=True),
    sa.Column('first_forum_limitation', sa.Text(), nullable=True),
    sa.Column('first_appeal_forum', sa.Text(), nullable=True),
    sa.Column('first_appeal_authority_id', sa.UUID(), nullable=True),
    sa.Column('first_appeal_limitation', sa.Text(), nullable=True),
    sa.Column('second_appeal_forum', sa.Text(), nullable=True),
    sa.Column('second_appeal_authority_id', sa.UUID(), nullable=True),
    sa.Column('second_appeal_limitation', sa.Text(), nullable=True),
    sa.Column('high_court_jurisdiction', sa.Text(), nullable=True),
    sa.Column('supreme_court_route', sa.Text(), nullable=True),
    sa.Column('interim_relief_available', sa.Boolean(), nullable=True),
    sa.Column('relief_types', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['first_appeal_authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['first_forum_authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['second_appeal_authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stamp_duty_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('article_number', sa.Text(), nullable=True),
    sa.Column('instrument_description', sa.Text(), nullable=True),
    sa.Column('instrument_category', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('proper_stamp_duty', sa.Text(), nullable=True),
    sa.Column('duty_formula', sa.Text(), nullable=True),
    sa.Column('duty_amount_fixed', sa.Numeric(), nullable=True),
    sa.Column('duty_percentage', sa.Numeric(), nullable=True),
    sa.Column('duty_on_value_of', sa.Text(), nullable=True),
    sa.Column('maximum_cap', sa.Numeric(), nullable=True),
    sa.Column('minimum_floor', sa.Numeric(), nullable=True),
    sa.Column('who_pays', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('exemptions', sa.Text(), nullable=True),
    sa.Column('related_transaction_type_id', sa.UUID(), nullable=True),
    sa.Column('notification_reference', sa.Text(), nullable=True),
    sa.Column('e_stamping_available', sa.Boolean(), nullable=True),
    sa.Column('adjudication_required', sa.Boolean(), nullable=True),
    sa.Column('penalty_for_deficit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['related_transaction_type_id'], ['transaction_types.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_provision_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_type_id', sa.UUID(), nullable=True),
    sa.Column('structural_unit_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('relevance_type', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_units.id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transaction_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_provision_links')
    op.drop_table('stamp_duty_schedules')
    op.drop_table('rights_and_remedies')
    op.drop_table('repeal_mappings')
    op.drop_table('rate_slab_schedules')
    op.drop_table('point_in_time_snapshots')
    op.drop_table('judicial_interpretations')
    op.drop_table('form_templates')
    op.drop_table('fee_schedules')
    op.drop_table('delegation_of_powers')
    op.drop_table('definitions')
    op.drop_table('cross_references')
    op.drop_table('conditions_precedent_consequent')
    op.drop_table('compliance_obligations')
    op.drop_table('authority_provision_links')
    op.drop_table('applicability_conditions')
    op.drop_table('amendment_history')
    op.drop_table('structural_units')
    op.drop_table('notifications_circulars')
    op.drop_table('authorities')
    op.drop_table('transaction_types')
    op.drop_table('documents')
    # ### end Alembic commands ###
